[package]
name = "abc-to-midi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abc-parser = "0.3.0"
midly = "0.5.2"

[dev-dependencies]
rstest = "0.12.0"
